kie-issues#1670: Migrate Apache licenses check to apache rat 0.17.x (#4154)
* kie-issues#1670: Migrate Apache licenses check to apache rat 0.17.x

Closes: https://github.com/apache/incubator-kie-issues/issues/1670

* trigger build

* trigger build

* Detect '!' character that is signal of Unapproved files

* Replace deprecated '-E' by '--input-exclude-file'

* Rat exclude 'quarkus/addons/opentelemetry/runtime/src/main/resources/META-INF/kogito.addon'

diff --git a/.github/workflows/ci_check_license_headers.yaml b/.github/workflows/ci_check_license_headers.yaml
--- a/.github/workflows/ci_check_license_headers.yaml
+++ b/.github/workflows/ci_check_license_headers.yaml
@@ -33,8 +33,17 @@ jobs:
 
       - name: Download Apache RAT
         run: |
-          curl -LO https://repo1.maven.org/maven2/org/apache/rat/apache-rat/0.16.1/apache-rat-0.16.1.jar
+          curl -LO https://repo1.maven.org/maven2/org/apache/rat/apache-rat/0.17/apache-rat-0.17.jar
 
       - name: Run Apache RAT
         run: |
-          java -jar apache-rat-0.16.1.jar -d . -E .rat-excludes | grep "== File:" && echo "The files listed above are missing license headers." && exit 1 || echo "All files have license headers."
+          # Redirect output to .rat-reports file, continue even if RAT returns non-zero exit code because we want to print Unapproved documents
+          java -jar apache-rat-0.17.jar --input-exclude-file .rat-excludes -- . > .rat-reports 2>&1 || true
+          if grep -q "^! Unapproved:" .rat-reports; then
+            echo "❌ Apache RAT check FAILED - Files with unapproved licenses found:"
+            echo ""
+            grep "^! /" .rat-reports
+            exit 1
+          else
+            echo "✅ Apache RAT check PASSED - All files have approved licenses."
+          fi
