kie-issues#1613: Add `CI :: License headers` GitHub Actions workflow (#3714)
* Add license header

* Revert "Add license header"

This reverts commit 00cfcc576ecbf25385000527951183892bcf4844.

* Add license header

* revert beans.xml

* .rat-excludes and rat check action

* remove checkstyle.header.template

* OMG BPMN SPEC files license

* .rat-excludes fix format - escaping

* .rat-excludes

* storage-jpa license

* apache rat 17

* fix exit logic

* print rat check output

* align with other PRs of kie-issues#1613

* license text placeholder

* LICENSE SPEC

* Revert "LICENSE SPEC"

This reverts commit 3e4e2f87ec31c7b425eff0f51c6a337750c91bc2.

* List explicitely all files in the .rat-excludes

* Use apache-rat v0.16.1

* Everthing -> Everything

* BPMN LICENSE text

* CI :: License headers

* kogito-codegen-modules/kogito-codegen-processes-integration-tests/src/test/resources

* .bpmn[2] files

diff --git a/.github/workflows/ci_check_license_headers.yaml b/.github/workflows/ci_check_license_headers.yaml
--- a/.github/workflows/ci_check_license_headers.yaml
+++ b/.github/workflows/ci_check_license_headers.yaml
@@ -1,3 +1,4 @@
+#
 # Licensed to the Apache Software Foundation (ASF) under one
 # or more contributor license agreements.  See the NOTICE file
 # distributed with this work for additional information
@@ -5,14 +6,35 @@
 # to you under the Apache License, Version 2.0 (the
 # "License"); you may not use this file except in compliance
 # with the License.  You may obtain a copy of the License at
-# 
+#
 #   http://www.apache.org/licenses/LICENSE-2.0
-# 
+#
 # Unless required by applicable law or agreed to in writing,
 # software distributed under the License is distributed on an
 # "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 # KIND, either express or implied.  See the License for the
 # specific language governing permissions and limitations
 # under the License.
+#
 
-quarkus.native.auto-service-loader-registration=true
+name: "CI :: License headers"
+
+on:
+  pull_request:
+    types: [opened, synchronize, reopened, ready_for_review]
+
+jobs:
+  check:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Download Apache RAT
+        run: |
+          curl -LO https://repo1.maven.org/maven2/org/apache/rat/apache-rat/0.16.1/apache-rat-0.16.1.jar
+
+      - name: Run Apache RAT
+        run: |
+          java -jar apache-rat-0.16.1.jar -d . -E .rat-excludes | grep "== File:" && echo "The files listed above are missing license headers." && exit 1 || echo "All files have license headers."
